FROM muffato/ensembl-linuxbrew-compara-base

# Run the install several times in case it is incomplete
RUN brew install ensembl/cask/compara \
 || brew install ensembl/cask/compara \
 || brew install ensembl/cask/compara

