FROM muffato/ensembl-basic-dependencies-linuxbrew

# Run the install several times in case it is incomplete
RUN brew install ensembl/cask/compara-ncrnatrees
RUN brew install ensembl/cask/compara-ncrnatrees
RUN brew install ensembl/cask/compara-ncrnatrees

